READMEの作成
wahei628/Baller pull request #1
Opened 2024-02-15 17:58 UTC by wahei628

2024-02-17 05:37 UTC, ooooose commented
ご提出ありがとうございます！
今後PRには変更したファイルについて説明を記載していただくようお願いしますmm

以下コメントさせていただきますのでご確認お願いします！
>  バスケットボールができるコート(場所)を探すアプリです。
コートを探す以外にもその場で集まった人たちで遊べるようにサイト上で繋がれるようにできるような機能も考えています。
個人のレベルも選べることができて、初心者の方や本格的にプレイしている方でも使えるようになっています。


上記のうち、「コートを探す機能」、「集まった人たちが遊べるようにサイト上で繋がれるようにできる機能」について実装方針なども含めてどのように実現するのか教えてください。
GoogleMapAPIを使ってどのようにコートを探すのかや、どのような機能を実装することでユーザー同士をつなげるのかを明確にしたほうがいいと思った次第です。

2024-02-18 03:10 UTC, wahei628 commented
> 上記のうち、「コートを探す機能」、「集まった人たちが遊べるようにサイト上で繋がれるようにできる機能」について実装方針なども含めてどのように実現するのか教えてください。

コートを探す機能として現状考えているのはGoogle mapのPlaces APIで地図上に出てくるコートを取得する予定でいます。
＋αの機能として地図上に出てこないコート、または検索に引っかからないものなどに関してはユーザー自身でアプリ上に登録できる機能などもつけられたらなと考えています。

集まった人たちで遊べるようにするようにする機能としては、WebSocketを使用しチャット機能を実装しようと考えています。
募集主に対して参加の旨を述べて、コメントなどでその後どうするかなどをやりとりして頂ければと思っています。

2024-02-18 03:21 UTC, wahei628 commented
本リリース時使用予定のAPIを詳細に明示しました。

> 上記のうち、「コートを探す機能」、「集まった人たちが遊べるようにサイト上で繋がれるようにできる機能」について実装方針なども含めてどのように実現するのか教えてください。

コートを探す機能として現状考えているのはGoogle mapのPlaces APIで地図上に出てくるコートを取得する予定でいます。
＋αの機能として地図上に出てこないコート、または検索に引っかからないものなどに関してはユーザー自身でアプリ上に登録できる機能などもつけられたらなと考えています。

集まった人たちで遊べるようにするようにする機能としては、WebSocketを使用しチャット機能を実装しようと考えています。
募集主に対して参加の旨を述べて、コメントなどでその後どうするかなどをやりとりして頂ければと思っています。

2024-02-19 04:41 UTC, tmtkzk0823 commented
修正ありがとうございます。
以下、追加のコメントになります。

--- 

### 全体
 - > どんなサービスなのかを３行で説明してください。

上記のような、RUNTEQが提供しているREADMEのFormatにあらかじめ記載してある文言は削除してしまって大丈夫です。

### 機能
- `投稿機能`とありますが、MVP時点でどのような内容を投稿する予定かお聞きしたいです。

- また、`検索機能`とはどのような内容のものを検索する機能かもお聞きしたいです。

2024-02-21 08:59 UTC, wahei628 commented
READMEのFormatの削除、MVP・本リリース時の機能を変更しました。

> 投稿機能とありますが、MVP時点でどのような内容を投稿する予定かお聞きしたいです。
> また、検索機能とはどのような内容のものを検索する機能かもお聞きしたいです。

投稿機能に関して地図上で表示されない情報をユーザー自身で投稿してもらうような形で考えていました。
MVP段階では必要ないと思ったので本リリース時に実装したいと思います。

検索機能に関してはコートを探す際に都道府県別で探せればなと考えていました。
こちらはMVPリリース時に実装するべきと考え変更しました。

2024-02-22 05:40 UTC, kenchasonakai commented
マッチング確率についてですが、このアプリを使って全国のユーザーはどの程度マッチング出来ることを想定していますでしょうか？
バスケをしている人は知らない人と個人で会ってバスケをしたいモチベーションはあるんですかね？

2024-02-27 07:18 UTC, wahei628 commented
ご連絡遅くなり申し訳ございません。

> マッチング確率についてですが、このアプリを使って全国のユーザーはどの程度マッチング出来ることを想定していますでしょうか？

全国のバスケ人口が2021年に約281万人(20歳以上＋20歳未満)いますのでプレイヤー人口に関しては問題ないと思われます。
https://www.ssf.or.jp/thinktank/sports_life/data/basketball_0018.html
全国全ての箇所で募集しても集まらないかなと思い最初の方は政令指定都市など限定的な地域で行おうかなと思いました。
また私の友人、友人のつてで20〜30人ほどは集まるかなと考えています。
そこからプレイヤーが増えて頂ければと思っています。


> バスケをしている人は知らない人と個人で会ってバスケをしたいモチベーションはあるんですかね？

私の友人に聞いてみた所、知らない人と個人で会ってバスケをしてみたいという人はいました。
ただ普段一緒にバスケをする人がいない時やたまになどと限定的にはなってしまいました。

2024-02-29 01:21 UTC, Tsuchiya2 commented
私からもコメントします。

---

同様のアプリケーションがありましたが、マッチングする頻度・利用頻度が少ないためかマッチすることが稀といった印象でした。

個人的にはマッチング系のアプリケーションは上記の状態になりがちなため、ユーザーからのフィードバックが得にくいことが多く、リリースしても使用が少ないため、発展性・継続性が難しいといった傾向があります。

一度この案で進めるか再考してみてください。

2024-03-02 07:33 UTC, wahei628 commented
前の案を変更しました。
ご確認の程よろしくお願いします。


## ■サービス概要

バスケの自主練記録を残せるアプリです。
練習メニューもランダムで選んでくれることができ、
また近くのバスケットボールができる場所を検索できます。


## ■ このサービスへの思い・作りたい理由

私は中学から現在までバスケをしています。
その中で一人だと自主練しにいくのを躊躇ってしまう時がありました。
さらに自宅から遠いコートとかだと尚更行くのが大変な時がありました。
原因として一人だとモチベーションが続かない、単調な練習になってしまうからと考えられました。

そのためこのアプリを使用し、改善できる点を考えました。
モチベーションが続かない→記録を残し自身の頑張り具合が把握できる
単調な練習になる→練習メニューを選択し、（例：ドリブル、シュート等）ランダムで提案してくれることで新鮮味のある状態にしてくれる

ただ記録をつけるだけだとどうしても飽きが来てしまうと思います。
そのため週何回以上行ければトップページを違うデザインにする、労いのメッセージを表示するなど考えています。


## ■ ユーザー層について

バスケを行うユーザーでも、特に初心者に向けて考えています。
初心者は練習などが習慣付いていないと思うので習慣づけが大切かなと思いました。
https://www.basketballtutor.com/news/20083/


## ■サービスの利用イメージ

・その日行ったトレーニングの記録をつけていきます。
・Open AI APIを使用し、おすすめのトレーニングを提案してもらうことができいます。
・現在地情報を取得し、近くのバスケットボールコートを探せます。
  またカテゴリー機能で条件に当てはったコートも探せます。
・タグ機能でコート近くに自販機やお手洗いがあるかをある程度確認できます。


## ■ ユーザーの獲得について

Xを使っての拡散
友人に使ってもらい宣伝する


## ■ サービスの差別化ポイント・推しポイント

https://apps.apple.com/jp/app/homecourt-basketball-training/id1258520424?platform=iphone
Home CourtというARを使った練習メニューがあるアプリがありました。
こちらとの差別化として上記のアプリにないコートを探せる機能、
また練習メニューを提案してもらえる機能を追加したいと思いました。


## ■ 機能候補

MVPリリース時
・会員登録
・ログイン
・パスワードリセット機能
・検索機能
・プロフィール編集機能
・Xの投稿機能
・現在地の取得(Google Geolocation API)
・場所の取得(Google Places API)、
・おすすめトレーニングの提案(Open AI API)

本リリース時
・タグ機能
・自身のお気に入りコートの登録機能
・カテゴリー機能
・オートコンプリート機能
・コートの登録機能(地図上に表示されない、検索に引っかからない物)
・Google認証ログイン機能

## ■ 機能の実装方針予定

現在地の取得(Google Geolocation API)
場所の取得(Google Places API)、
おすすめトレーニングの提案(Open AI API)
Google認証ログイン機能

2024-03-03 07:31 UTC, O-H-K-N commented
修正ありがとうございます！

以下コメントです！
ご確認お願いいたします！

---

- コートを探せる機能ですが、Google Places API を使ってどのように探すかを教えていただいてもよろしいでしょうか？APIで「バスケットコートがある公園」などで検索してどの程度ヒットするのかと、検索に引っかからない場合がないかが気になりました！

> タグ機能でコート近くに自販機やお手洗いがあるかをある程度確認できます。

- こちらも同様にどのようにして探すのかの説明をお願いいたします！

2024-03-03 23:37 UTC, wahei628 commented
> コートを探せる機能ですが、Google Places API を使ってどのように探すかを教えていただいてもよろしいでしょうか？APIで「バスケットコートがある公園」などで検索してどの程度ヒットするのかと、検索に引っかからない場合がないかが気になりました！

Places API内のNearby Searchを使用して検索結果から半径何メートル以内か指定し、コートの情報を取得する予定です。
「町田市　バスケットコート」で検索をかけ、19件引っかかり、4件がコートなし、1件Google Map上では確認できなかった(Webサイトで存在が確認できた)です。
こちらに関して本リリース時に実装予定のコート登録機能を使用してもらう形で考えています。
コートなしに引っかかってしまうのは現状どのようにすれば良いかが思い浮かびませんでした。
別の案で都道府県、市区町村別でコートの情報が載っているサイトからスクレイピングで情報を得る方法か(規約上可能か確認)、自身で独自地図(コートにピンを差してMy mapとして使用)を埋め込む方法があるかと思われますが、上記の登録機能でいきたいと思いました。

> タグ機能でコート近くに自販機やお手洗いがあるかをある程度確認できます。

こちらに関してですが、完全手作業になってしまうかもしれないので廃止予定にします。
検索件数によっては自販機を探すアプリ(COKE ONのアプリ)やお手洗いを探せるアプリがあるみたいなのでそこからタグ付けしていければと思っています。

2024-03-04 09:47 UTC, tmtkzk0823 commented
> コートなしに引っかかってしまうのは現状どのようにすれば良いかが思い浮かびませんでした。

この場合、「一番近くのバスケットコートをおすすめする」などの機能が考えらるかと思いましたがいかがでしょうか？

> おすすめトレーニングの提案(Open AI API)

こちらは、文字ベースでおすすめするのでしょうか？
個人的には、おすすめされたトレーニングはどのようにやるのか、図か動画で確認したいと思いました。この県についてもお聞きしたいです。

2024-03-04 12:01 UTC, wahei628 commented
> この場合、「一番近くのバスケットコートをおすすめする」などの機能が考えらるかと思いましたがいかがでしょうか？

そちらの案で進めたいと思いました。

> こちらは、文字ベースでおすすめするのでしょうか？
個人的には、おすすめされたトレーニングはどのようにやるのか、図か動画で確認したいと思いました。この県についてもお聞きしたいです。

確かに動画とかがあった方がいいと思いました。
こちら本リリースでYouTube Data APIを使用し、YouTubeからトレーニング動画を取得していきたいと思いました。

2024-03-05 03:11 UTC, Tsuchiya2 commented
対応ありがとうございます。
私からもコメントします。

---

■その他
・ユーザー層の部分で初心者を想定していると書かれていますが、ご自身は中学から現在までバスケを経験されてきているとなると、このサービスの対象から外れてしまいますが、このサービスを１ユーザーとして楽しめそうかが気がかりになりました。
・上記を記載したのは、個人アプリはほとんど使われることが無いため、自分も使わないアプリだと、余計に利用されなくなり、サービスの改善や使用した人の意見や感想を集めにくくなりますし、また開発も楽しくないかと思ってのコメントになります。
・それでもこのサービスを最後まで、MVPリリース後も開発を続けられそうでしょうか。

重要なことかと思いますので、こちらで一旦お返しします。

2024-03-07 09:00 UTC, wahei628 commented
前の案を変更しました。
ご確認の程よろしくお願いします。

Outspire

■サービス概要
外に出かけるプランを提案してくれるサービスです。
診断方式で自分に合ったタイプで外に出る提案をしてくれます。
外出先へのレビューや評価などすることもできます。


■ このサービスへの思い・作りたい理由
私自身、出不精な部分があり休みの日は1日家にいることも珍しくありません。
そのため、不完全燃焼な休日だったと思ったり、楽しくなかったなど後悔することも多かったです。
なぜ外に出ないのかと考えたら(私の場合)、
1、そもそも面倒臭い(どこに行くか考える事や、調べたりする事、天候など)
2、やりたいことが見つからない

この二つを私の作るアプリで解消できるかなと考えました。

勉強や筋トレなどは自宅でできるものだと思います。
ただ自宅だとどうしてもモチベーションが上がらなかったり、サボってしまうことがあります。
カフェで勉強したり、ジムに行って後悔したことは一度もないため同じ悩みを持つ人に届けばと思いました。


■ ユーザー層について
休みなどで外出したいけど予定を決めるのが憂鬱な人
特にやりたいことがない人
RUNTEQ生や資格勉強してる人


■サービスの利用イメージ
診断で自分に合った外出先を見つけてくれます。
勉強系だったらカフェやコワーキングスペース、
遊び系だったらダーツやカラオケなど現在地から近くの場所を探してくれます。
診断は10〜15問程度でその時の気分(リラックスしたい、ストレス発散したいなど)によって分けて考えます。
外出先のレビューや評価をすることができます。
Xの共有機能でどこに出かけるか(カフェやカラオケ等)共有できます。
またその日の天候からアドバイスや一言をもらえることができます。


■ ユーザーの獲得について
Xでの拡散
友人からの宣伝


■ サービスの差別化ポイント・推しポイント
以下のアプリが似ている感じがしました。
https://ppap.kinto-jp.com/prismjapan

旅のプランや道中の様子などを提案してくれるみたいです。
私のアプリは外に出ることを第一に考えており、いろんな提案をしてくれるのでその点で差別化できると考えました。


■ 機能候補
MVPリリース時
・会員登録
・ログイン
・パスワードリセット機能
・プロフィール編集機能
・診断機能
・Xの投稿機能
・現在地の取得(Google Geolocation API)
・場所の取得(Google Places API)

本リリース時
・Google認証ログイン機能
・天候からアドバイス(Open AI API、Open Weather API)
・外出先へのレビュー・評価(口コミ的なイメージです)


■ 機能の実装方針予定
・現在地の取得(Google Geolocation API)
・場所の取得(Google Places API)
・Google認証ログイン機能
・天候からアドバイス(Open AI API、Open Weather API)

2024-03-07 10:11 UTC, tarakish requested changes
新案確認しました。以下コメントです！

---
■ターゲット
> RUNTEQ生や資格勉強してる人

こちらのターゲットは他２つのターゲットと少しズレると感じました。
追加している理由があればご説明をお願いできますか？

■差別化、売りのポイント
> 私のアプリは外に出ることを第一に考えており、いろんな提案をしてくれるのでその点で差別化できると考えました。

こちらなんとなくのニュアンスは伝わりますが、もう少し具体的に言語化してみていただけますか？
差別化ポイントが曖昧だとなぜこのサービスを使うのかの訴求力が弱くなってしまうので、この段階でしっかり伝えられるようにしておくと良さそうです。

2024-03-07 20:53 UTC, wahei628 commented
> こちらのターゲットは他２つのターゲットと少しズレると感じました。
追加している理由があればご説明をお願いできますか？

私自身、ちょっと休憩してから勉強再開しようと思っていたら、
大幅に休憩し過ぎたり途中で寝てしまったりなどがありました。
同じような悩みを持っている人はいらっしゃるかもしれないので追加してみました。

> こちらなんとなくのニュアンスは伝わりますが、もう少し具体的に言語化してみていただけますか？
差別化ポイントが曖昧だとなぜこのサービスを使うのかの訴求力が弱くなってしまうので、この段階でしっかり伝えられるようにしておくと良さそうです。

今回作成予定のサービスは予定を決めるのが億劫な人向けに考えています。
既に計画があり外出する人よりかは、外出しないとと考えているが、
計画立てるのは大変と思っている方に使ってもらおうと考えてます。
その点が一番の差別化ポイントだと思いました。

2024-03-08 06:38 UTC, kenchasonakai commented
LGTMです！

機能面少し弱いので、実装を進めながら高機能な検索機能(オートコンプリート・マルチカラム検索)を導入したり、よくいくところの近くのおすすめ店舗などを出したりするサジェスト機能など機能面に厚みを持たせられるように考えていくと良いと思います

2024-03-09 01:20 UTC, wahei628 commented
ありがとうございます！

> 機能面少し弱いので、実装を進めながら高機能な検索機能(オートコンプリート・マルチカラム検索)を導入したり、よくいくところの近くのおすすめ店舗などを出したりするサジェスト機能など機能面に厚みを持たせられるように考えていくと良いと思います

承知しました。

2024-03-09 01:20 UTC, merged